const express = require("express");
const cors = require("cors");
const app = express();
const patientrouter = require("./patient/patient");
const DoctorRouter = require("./doctor/doctor");
const AppointmentRouter = require("./appointment/appointment");
const PaymentRouter = require("./payment/payment");
const Roomrouter = require("./Room/room");
const PatientUserRouter = require("./userSignup/patientusers/patientusers");
const DoctorUserrouter = require("./userSignup/doctorusers/doctorusers");
const patientauthRouter = require("./logauth/patientuser/patientlogauth");
const doctorauthRouter = require("./logauth/doctoruser/doctorlogauth");
const adminauthRouter = require("./logauth/admin/admin");
const DoctorSpecialistData = require("./Specialistdata/Specialist");
const Departmentlist = require("./Department/department");
const userpasswordreset = require("./forget/password");
app.use(cors());
app.use(express.json());
app.use(express.Router());
app.use("/patient", patientrouter);
app.use("/Doctor", DoctorRouter);
app.use("/Appointment", AppointmentRouter);
app.use("/payment", PaymentRouter);
app.use("/room", Roomrouter);
app.use("/user/signup/patient", PatientUserRouter);
app.use("/user/signup/doctor", DoctorUserrouter);
app.use("/patientauth", patientauthRouter);
app.use("/doctorauth", doctorauthRouter);
app.use("/AdminLogin", adminauthRouter);
app.use("/Doctor/Speciallist/data", DoctorSpecialistData);
app.use("/hospital/departmentlist", Departmentlist);
app.use("/user", userpasswordreset);
app.listen(4000, console.log("server is runnning on 4000"));
